version: '3'
services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200 # probably don't want to actually expose these ports on production
      - 9300:9300
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

