networks:
  elastic:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
