services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9400:9400 # probably don't want to actually expose these ports on production
      - 9500:9500
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      - ./es_snapshots:/usr/share/elasticsearch/snapshot
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    ports:
      - 5602:5601
    depends_on:
      - elasticsearch

