POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "app_id": "1529135893"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 1100
etag: W/"44c-oEuHQ/xXVPtCaecsFK2Jnq7oa+g"
date: Sat, 03 Feb 2024 17:54:34 GMT
connection: close
###
GET http://localhost:8080/appList?start=0

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 61
etag: W/"3d-wmdQM/6HpPOsTg1PlkFtrQy7xQc"
date: Thu, 08 Feb 2024 20:25:45 GMT
connection: close
###
POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "from": "21",
    "size": 20,
    "app_id": "1529135893"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 1110
etag: W/"456-quOufe7lKu4sn8O7OPvwN2NO2fk"
date: Sat, 03 Feb 2024 17:55:16 GMT
connection: close
###
POST http://localhost:8080/api/runs 

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 1420
etag: W/"58c-d2iTttaxVQ/7Vnm6KPRKI+fKc24"
date: Thu, 08 Feb 2024 20:21:49 GMT
connection: close
###
POST http://localhost:8080/api/get/
Content-Type: application/json
{
    "app_id": "1529135893",
    "run_id": "run_00069"

}
###
POST http://localhost:8080/api/search/app_name
Content-Type: application/json
{
    "app_name": "sen"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 275
etag: W/"113-sdayCykwuWnLoLwXd6qBZm40Lys"
date: Thu, 08 Feb 2024 20:06:07 GMT
connection: close