POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "app_id": "1529135893"
}
###
POST http://localhost:3000/api/search/app_id
Content-Type: application/json
{
    "from": "21",
    "size": 20,
    "app_id": "1529135893"
}
###
GET http://localhost:8017/appList?start=0
###
GET http://localhost:8017/appList?start=0&run=run_00069
###
GET http://localhost:8017/runs
###
GET http://localhost:8017/getApp?id=1588684626
###
POST http://localhost:8080/api/get/
Content-Type: application/json
{
    "app_id": "1529135893",
    "run_id": "run_00069"
}
###
POST http://localhost:8080/api/search/app_name
Content-Type: application/json
{
    "app_name": "sen"
}
###
GET http://localhost:8017/translateApp
Content-Type: application/json
{
    "privacy_types": ["大概位置", "裝置 ID", "產品互動", "廣告資料", "效能資料", "當機資料"]
}
###
GET http://localhost:8017/graph14Helper?index=dnc
###
GET http://localhost:8017/graph14
###
GET http://localhost:8017/graph15
###
GET http://localhost:8017/latestIndex
###
GET http://localhost:8017/longitude
###
GET http://localhost:4000/elastic-data
